### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by mrsempress** [mcordts/cityscapesScripts#100]
When I use following command, I get UnicodeDecodeError.
`git clone https://github.com/mcordts/cityscapesScripts.git`
`cd cityscapesScripts/`
 `python setup.py build_ext install`
The error is 

> Traceback (most recent call last):
>   File "setup.py", line 27, in <module>
>     readme = f.read()
>   File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
>     return codecs.ascii_decode(input, self.errors)[0]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 302: ordinal not in range(128)
So, how can solve it?

**Comment by yutongred** [comment]
I have the same problem how to solve it?
