### ISSUE TITLE
SegNet's results

### ISSUE THREAD

**Issue by vigorous0503** [mcordts/cityscapesScripts#11]
[Hi](url) all,

I just use the Cityscapes Dataset to train a SegNet model and make some experiments with it.
And now, I want to evaluate my results on val set, and I also know that we need to have full resolution if I want to submit to the evaluation server.

But, I am confused that why I see the result of SegNet on official benchmark suite was evaluated on subsample with factor 4 at test time?
Is there another official code for the result which is subsample with factor 4 ?
Because I must compare my result with that in the same way.
![default](https://cloud.githubusercontent.com/assets/16635718/18004684/074be9b6-6bc8-11e6-9908-4a6117d85aa4.PNG)

And, I want to ask all that could anybody share the trained model on the Cityscapes dataset if you did?

Thanks all!

Best,
Gary

**Comment by mcordts** [comment]
Hi Gary,

The subsample factor primarily corresponds to the input image.

You are right, the evaluation server requires the prediction results to
have the original resolution. The simplest is to apply an upsampling
without interpolation, but this is the responsibility of the authors and
_not_ performed automatically. I think also in the case of SegNet, the
authors used this type of upsampling.

The only public model trained on Cityscapes that I am currently aware of is
Dilation10:
https://github.com/fyu/dilation

Best,
Marius


2016-08-26 3:40 GMT+02:00 B.C Tsai <notifications@github.com>:

**Comment by vigorous0503** [comment]
Hi mcordts,

Thank you very much for your quick and detail response.

I will try the things what you suggested.

Best.
Gary
