### ISSUE TITLE
how to download your dataset with wget

### ISSUE THREAD

**Issue by gaopeng-eugene** [mcordts/cityscapesScripts#13]

**Comment by mcordts** [comment]
Unfortunately, that is not possible.

**Comment by jianchao-li** [comment]
Hi, @gaopeng-eugene, @mcordts.

I found [this blog](https://neppo.net/blog/2017/11/1121_wget_cityscapes/) written in Japanese which gives the following way to download the cityscapes dataset using `wget`. I tried it and it worked.

Step 1

```bash
wget --keep-session-cookies --save-cookies=cookies.txt --post-data 'username=USERNAME&password=PASSWORD&submit=Login' https://www.cityscapes-dataset.com/login/
```

Step 2

```bash
wget --load-cookies cookies.txt --content-disposition https://www.cityscapes-dataset.com/file-handling/?packageID=ID
```

**Comment by bitwangdan** [comment]
@jianchao-li hi, sorry to bother you, can you tell me how to use this?
