### ISSUE TITLE
How to use the installed cityscapesScripts module?

### ISSUE THREAD

**Issue by Bjoux2** [mcordts/cityscapesScripts#134]
how to use the tools like csDownload, csViewer of the installed module?

for example, 
I tried:

'csDownload cityscapes' 

No doubt, it doesn't work

**Comment by Bjoux2** [comment]
besides, I downloaded the gtFine dataset manually, I tried: csViewer .../berlin...png  or csViewer .../berlin...json, and it doesn't work too.

**Comment by ncgaehle** [comment]
Set your environment variable CITYSCAPES_DATASET to the path of the dataset and then run csViewer.
https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/viewer/cityscapesViewer.py#L1404
