### ISSUE TITLE
How to get other packages of datasets?

### ISSUE THREAD

**Issue by liruihao** [mcordts/cityscapesScripts#14]
Dear Marius Cordts

I want to use 'all_demoVideo.zip' and 'leftImg8bit_sequence_trainvaltest.zip'. How could I get these datasets? I sent an email to 'mail@cityscapes-dataset.net', but get no reply.

Thank you very much for your help.

Best wishes,

Ruihao

**Comment by mcordts** [comment]
Writing an email is the correct way.

**Comment by abdur75648** [comment]
Hi @liruihao 
If you have got the "leftImg8bit_sequence_trainvaltest" (324GB) dataset, could you share just the "validation" split of it with me, please? I am having trouble downloading it.
Let me know if it's possible for you to share a download link with me on my email
