### ISSUE TITLE
Question about the definition of yaw, pitch and yaw in 3D bbox labels

### ISSUE THREAD

**Issue by prismformore** [mcordts/cityscapesScripts#158]
Hi, may I know where could I find a clear definition of yaw, pitch, and yaw angles used in this 3d dataset? For example, the **coordinate system used and the value range** of these angles. I couldn't find them in the paper and the evaluation code. Thank you very much.

It would be better if we can also have a conversion tutorial between the actually used quaternion labels in data and those three Euler angels, although we can directly use the tools in evaluation code.

**Comment by ncgaehle** [comment]
Please checkout the following files:

- https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/box3dImageTransform.py
- https://github.com/mcordts/cityscapesScripts/blob/master/docs/Box3DImageTransform.ipynb
- https://github.com/mcordts/cityscapesScripts/blob/master/docs/csCalibration.pdf

and see 
`All GT annotations are given in the ISO coordinate system V and hence, the evaluation requires the data to be available in this coordinate system.`. The used Euler angles are the ones in coordinate system V.

**Comment by prismformore** [comment]
@ncgaehle Thank you very much for your reply. The definition of yaw-pitch-roll is important for me because I am considering the transformation between the local yaw-pitch-roll angles and global yaw-pitch-roll angles.

I have read these files before and since there is still no clear definition of the yaw, pitch and roll in them may I confirm whether my understanding is correct:

For `rotation_V` obtained from `box3d_annotation.get_parameters(coordinate_system=CRS_V)`, we can get yaw, pitch and roll by transforming the quaternion into Eular angles with `rotation_V.yaw_pitch_roll`. The obtained yaw is defined as the angle between vehicle direction and **x-axis** (on x-y plane), pitch is the angle between vehicle direction and **z-axis** (on z-x plane), roll is the angle between vehicle direction and **y-axis**  (on z-y plane).

After we get `rotation_S` with `box3d_annotation.get_parameters(coordinate_system=CRS_S)` , we can get yaw, pitch and roll by transforming the quaternion into Eular angles with `rotation_S.yaw_pitch_roll`.

Here (under CRS_S), the obtained yaw is defined as the angle between vehicle direction and **z-axis** (under z-x plane), the pitch is the angle between vehicle direction and the **negative y-axis** (y-z plane),  roll is the angle between vehicle direction and **negative x-axis**  (on x-y plane).

If so the definition of this yaw is different from that used in [mmdetection3D](https://github.com/open-mmlab/mmdetection3d/blob/92d5a87e97b058621fa55a6f073a287e5ecd1a27/mmdet3d/core/bbox/structures/cam_box3d.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L10), right?

Your help is really appreciated!

**Comment by ncgaehle** [comment]
CRS_V is the coordinate frame in which all calculations (including yaw, pitch, and roll) are done for the evaluation. In CRS_V it is like this: 
![image](https://user-images.githubusercontent.com/63056374/148905211-22ea37f9-ba92-473b-9a6a-1c20f6fe98ee.png)
If you do the calculations in another coordinate frame the angles for sure are different.

**Comment by prismformore** [comment]
@ncgaehle thank you. I understand the concept of these three angles. But I am not sure about the **exact definition** of them in CRS_V e.g. the definition of yaw can be the angle between the vehicle direction and x-axis (on x-y plane), **or** the angle between the vehicle direction and negative y-axis (on x-y plane), this should influence how we calculate the gobal-local yaw transformation, right?

![image](https://user-images.githubusercontent.com/14089338/148919757-a0db6042-33ee-49c3-952e-93fb4b69bdf6.png)
