### ISSUE TITLE
[critical bug]  evalInstanceLevelSemanticLabeling read bw png bug

### ISSUE THREAD

**Issue by joyousrabbit** [mcordts/cityscapesScripts#16]
It's a known bug of PIL: the np.array cannot convert the bw png image. 
http://stackoverflow.com/questions/2761645/error-converting-pil-bw-images-to-numpy-arrays

The solution is simple. Change the image to grayscale before being converted by np.array.
In your def assignGt2Preds(gtInstancesOrig, gtImage, predInfo, args):
        # Read the mask
        predImage = Image.open(predImageFile)
        predImage = predImage.convert("L");               <---add this line pls, line 302
        predNp    = np.array(predImage)

**Comment by mcordts** [comment]
Thank you for pointing this out. I added the line.
