### ISSUE TITLE
The red point isn't following the mouse after open zoom window when using the annotation tool

### ISSUE THREAD

**Issue by githubfragments** [mcordts/cityscapesScripts#17]
Hi, I use the annotation tool to annotate images, and find when the zoom window is open, the red isn't following the mouse, as shown in image below. I can't figure out the reason. Is this normal? Could you help to fix it? @mcordts 

![3](https://cloud.githubusercontent.com/assets/16164389/24320922/d62074de-117a-11e7-9591-8ab221c8402a.png)

**Comment by mcordts** [comment]
Actually that's on purpose to allow for a precise annotation. 
If you don't like this behavior, you could try to set the sensitivity to 1 in [line 2042](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/annotation/cityscapesLabelTool.py#L2042)

**Comment by githubfragments** [comment]
Thank you. I got it. That really does help a lot.

**Comment by Bhomik** [comment]
@mcordts the red point is following the curson on setting the sensitivity to 1 but the zoomed image keeps on moving along with the cursor which doesn't allow precise annotation. Is there some way by which I can stop the movement of the window.
