### ISSUE TITLE
Error when annotating an image from scratch 

### ISSUE THREAD

**Issue by avijit9** [mcordts/cityscapesScripts#18]
I am trying to annotate an image from scratch. So, initially I don't have any label files for that image. But I am facing the following error after creating the new object and selecting its label from the dropdown list- 

```
Traceback (most recent call last):
  File "cityscapesLabelTool.py", line 944, in newObject
    self.appendObject( label , self.drawPoly )
  File "cityscapesLabelTool.py", line 2347, in appendObject
    for obj in self.annotation.objects:
AttributeError: 'NoneType' object has no attribute 'objects'

```
Apparently it seems that `self.annotation` is of `NoneType. `

**Comment by mcordts** [comment]
Sorry for the delay. Should be fixed now.
