### ISSUE TITLE
Evaluation issue from trainIds to labelIds

### ISSUE THREAD

**Issue by animebing** [mcordts/cityscapesScripts#19]
My output is in the form of trainIds, but in your github, you say the evaluation is done in labelIds, so I have to convert the trainIds to labelIds first, but in the file helpers/labels.py, I find one trainId is mapped to multiple labelId, so I am confused that which labelId I should convert to, please give me a detail about it, which will help me a lot, thanks

**Comment by mitalbert** [comment]
@animebing 
I also trained network using TrainId-s, hence the output pixels values are 0-18. Have you found a way to use this evaluation script for TrainIds?
