### ISSUE TITLE
Can not download cityscapes dataset

### ISSUE THREAD

**Issue by q252558242** [mcordts/cityscapesScripts#23]
Hi,Marius Cordts.
Sorry to disturb you.I'm a postgraduate of Southeast University. Our team want to get cityscapes dataset for research learning, I've registered in the dataset website for several days,  but I have not gotten the human approval.If you are convenient,please tell us how to get the dataset easily.I am looking forward for your reply.

**Comment by mcordts** [comment]
Closing issue as this is not related to the code. Please contact us via email in case your problem remains. Thank you.

**Comment by q252558242** [comment]
I'm so sorry for what I did.But I've contacted some of you by email but  haven't received reply.And I can not open your personal website link in the cityscapes dataset.So I did this without any choice.
