### ISSUE TITLE
annotation mistakes

### ISSUE THREAD

**Issue by amiltonwong** [mcordts/cityscapesScripts#24]
Hi, @mcordts ,

Just find the annotation mistakes in train ground-truth file "aachen_000053_000019_gtFine_labelIds.png", the car at the center is mistakenly annotated as id 16 (tunnel).

**Comment by mcordts** [comment]
Hi, 
Thank you for pointing this out. Unfortunately, annotation mistakes can occur, even after extensive quality control. However, updating the data for a single mistake causes all previous submissions to be outdated. Thus, we decided to collect these mistakes and if there is a significant amount, we might update the dataset with a new release.
