### ISSUE TITLE
How to get the camera parameters?

### ISSUE THREAD

**Issue by ZhengtianXu** [mcordts/cityscapesScripts#26]
I want to know the camera parameters such as is the distance between two cameras and the focal length of camera. The README file says that csCalibration.pdf contains these parameters but I cannot find it. Can you tell me about this? Thanks very much.

**Comment by mcordts** [comment]
Hi, you can contact as via email requesting for the respective packages. The document you are referring to does not contain any values, it only describes the setup and calibration parameters.
