### ISSUE TITLE
how to create new annotations in polygonal format?

### ISSUE THREAD

**Issue by wuyu1008** [mcordts/cityscapesScripts#27]
I add new image and open it by cityscapesLabelTool.py. 
Then I draw one polygonal in image, but can not save it and generate JSON file.
Any suggestion?

**Comment by lalitheranti** [comment]
Yes me too. Please help. same issue.

**Comment by DenisN03** [comment]
Faced the same problem. Anybody decided it?

**Comment by Bhomik** [comment]
Are you getting any error after drawing the polygon ?

**Comment by cslxiao** [comment]
On line 2360, change `CsObject` into `CsPoly`.

**Comment by mcordts** [comment]
Is fixed now.
