### ISSUE TITLE
Different "*_gtFine_labelTrainIds.png" generation result

### ISSUE THREAD

**Issue by EthanZhangYi** [mcordts/cityscapesScripts#29]
Hi, Cityscapes Team

I generated the `*_gtFine_labelTrainIds.png` files with two different approaches and got **different** results.

[1] Files are generated with [`createTrainIdLabelImgs.py`](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py) supplied in this project.
[2] Files are generated from `*_gtFine_labelIds.png`  supplied in dataset with matlab code below:
```matlab
infile = 'gtFine/train/aachen/aachen_000000_000019_gtFine_labelIds.png';
outfile = 'gtFine/train/aachen/aachen_000000_000019_gtFine_labelTrainIds_matlab.png';
img = imread(infile);
outimg = uint8(ones(size(img))*255);
mapping = [7, 8, 11, 12, 13, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 31, 32, 33];
for idx = 1:19
    outimg(img == mapping(idx)) = idx-1;
end
imwrite(outimg, outfile);
```

The  `*_gtFine_labelTrainIds.png`  results generated from the 2 methods above are different at the edge pixels of objects & staffs in the images. See diff image below for your reference (white pixels are those with different labels).
![aachen_000000_000019_gtfine_labeltrainids_diff](https://user-images.githubusercontent.com/13479831/30195621-1d4b92e0-948d-11e7-899a-0ac7e2943bc6.png)

So **how to deal with this inconsistency?**

Thanks~

**Comment by mcordts** [comment]
I assume that this is due to changes in the python module Pillow. Could you please double check by going back to version 2.3.0 (e.g. sudo pip install Pillow==2.3.0), rerun createTrainIdLabelImgs.py and then your matlab script?

**Comment by EthanZhangYi** [comment]
@mcordts   Thanks, that is exactly the reason.
So we need to generate TrainIdLabel with Pillow==2.3.0, right?

**Comment by LeonJWH** [comment]
I have occured the same problem when I generate labelId png annotations, and I just use them even if there are defferences at the edges. But when I generated instanceId png annotations, I found that in one single instanceId png annotation, different in.stances have the same color which related to a unique class id.
Do you have any suggestions?
