### ISSUE TITLE
Why the BitDepth of xxxxxx_gtFine_color.png is 32bits in Windows?

### ISSUE THREAD

**Issue by csjfwang** [mcordts/cityscapesScripts#30]
Hello @krosaen @lucasb-eyer @MarvinTeichmann @mohomran @mcordts ,

When i check the labels in gtFine ,i found that the BitDepth of labelid is 8 bit, that of instanceId is 16 bit ,while the BitDepth of color is 32 bit.
Why is it 32 bit, and if i can just use it as 24 bit?

Thanks a ton!

**Comment by sr425** [comment]
I would asume that the image is stored as a png with alpha channel, thus leading to 4*8bit =32bit.
As far as I could see these images do not use the alpha channel, thus it should be save to remove it.
In general they seem only to be for visualication, so removing the channel should not hurt.
Hope that helps.
