### ISSUE TITLE
instance label in ******_gtFine_instanceIds.png

### ISSUE THREAD

**Issue by LeonJWH** [mcordts/cityscapesScripts#32]
I use the tool **json2instanceImg.py** to generate instance labels, but in the png image genereted by **json2instancImg.py** , different car instances(for example) seem to have the same label. 
As well, after i colored  the png image, i found that the color of different car instances have the same color.
Also with other classes such as person, different persons have the same instance label.

In **json2instancImg.py**, different instances are drawed with a unique id combined of class id and instance id, but in result png images, i can't find the defference between labels of instances.
Could you give some advice? 
Thx a lot! 
![mask](https://user-images.githubusercontent.com/17867054/30631694-b6999b52-9e17-11e7-8fd9-0ac3f96643f9.png)

**Comment by mcordts** [comment]
Did you make sure to properly read/write the 16 bit png images? The range of values of the instance ID images is 0...65535. Please make sure that you have any values >255, otherwise the image loading is the issue.

**Comment by LeonJWH** [comment]
Ok, I find out that it was because I loaded the 8 bit png images, loading png images with 16 bit is all right. Thank you very much!

**Comment by Tranbaber** [comment]
Hi, I would like to ask how to generate Cityscapes datasets that can be used for **instance segmentation**? After I do the format conversion using the script in the Cityscapes project, it doesn't differentiate the instances with different colors.
For example:
![aachen_000000_000019_gtFine_instanceIds](https://github.com/mcordts/cityscapesScripts/assets/142142591/ea44af4c-377e-4298-bf88-142705dd0abf)
@mcordts @wenhe-jia
