### ISSUE TITLE
any tutorial to use this tool to annotating image datas ?

### ISSUE THREAD

**Issue by ZhengPan2014** [mcordts/cityscapesScripts#33]
any tutorial to use this tool to annotating image data, I just download this repository and run the executable *.py file, there was same error warning like this:
![image](https://user-images.githubusercontent.com/15884732/31315011-12786ba6-ac41-11e7-868e-de6b25be5525.png)
then, I try to guess what that means, and do some configurations. But fail, if authors can shows us a simple tutorial. I believe that the most wasting time finding out how to using this tool can be saved for me and people like me.
my great respect to authors!

**Comment by touristCheng** [comment]
I meet the same problem, do you fix it now? Thanks! @ZhengPan2014

**Comment by ZhengPan2014** [comment]
@touristCheng  I just fixed the loading path in the script instead of adding env variable and it works.

**Comment by Shuhui11** [comment]
@ZhengPan2014 I am facing the same issue where the data is not found. You mentioned fixing the loading path, where (e.g. line) do I fix it at?

**Comment by ZhengPan2014** [comment]
@Shuhui11 [https://github.com/mcordts/cityscapesScripts/blob/4b6e5154281617660d8347e6c7109686af239317/cityscapesscripts/annotation/cityscapesLabelTool.py#L638](url)

**Comment by ZhengPan2014** [comment]
@Shuhui11 [https://github.com/mcordts/cityscapesScripts/blob/4b6e5154281617660d8347e6c7109686af239317/cityscapesscripts/annotation/cityscapesLabelTool.py#L638](url).

**Comment by Shuhui11** [comment]
@ZhengPan2014 thanks a lot for the prompt reply. I clicked on the link and it says no result matched my search. Is there another link where I can refer to?

**Comment by ZhengPan2014** [comment]
@Shuhui11 line 638 of cityscapesLabelTool.py.

**Comment by Shuhui11** [comment]
@ZhengPan2014 ok! I am not exactly sure what is the format of the path that I should input.

I have the folder of cityscapes dataset on my desktop. Within the folder, there is the cityscapesScripts from github, the gtFine and leftImg8 folders.

I changed line 638 from csPath = os.path.join(os.path.dirname(os.path.realpath(__file__)),'..','..') to csPath = '/Users/myname/Desktop/CITYSCAPES_DATASET/', but the same message of no data found still pops up. Is there something else that I need to add in to in my path?
