### ISSUE TITLE
How can we have access to [leftImg8bit_sequence_trainvaltest.zip]?

### ISSUE THREAD

**Issue by htcr** [mcordts/cityscapesScripts#35]
Hi authors,
Cityscape is an excellent work, however, we are strongly looking forward to the full video train-test dataset. Could you please tell us what does "available upon request" exactly mean? Are there any prerequisites?
Many many thanks and best wishes!

**Comment by warmkid** [comment]
hi bro, do you fix the problem? i have the same confusion.

**Comment by mcordts** [comment]
please send us an email listing the packages you need. thank you.
