### ISSUE TITLE
 can't add a new polygonal. locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by giyagaga** [mcordts/cityscapesScripts#36]
hi, I used the cityscapesLabelTool to label new images, but I just draw only one polygonal in image, i can't add a new polygonal,  should i change the 'us_us'?
________________________________________________________________________
Traceback (most recent call last):
  File "cityscapesscripts/annotation/cityscapesLabelTool.py", line 943, in newObject
    self.appendObject( label , self.drawPoly )
  File "cityscapesscripts/annotation/cityscapesLabelTool.py", line 2364, in appendObject
    obj.updateDate()
  File "cityscapesscripts/helpers/annotation.py", line 102, in updateDate
    locale.setlocale( locale.LC_ALL , 'us_us' )
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by guantinglin** [comment]
I have the same issue.
Did you solve it?

**Comment by Bhomik** [comment]
Please update line number 58 
with 
locale.setlocale( locale.LC_ALL , 'en_US.utf8' )

Let me know if it solves your problem :)

**Comment by cslxiao** [comment]
If you are annotating your own images, just simply comment the try-execpt code block.

**Comment by mcordts** [comment]
I hope that helped, updated the code.
