### ISSUE TITLE
Cityscapes Dataset and Caffe

### ISSUE THREAD

**Issue by Almo1982** [mcordts/cityscapesScripts#4]
Hi all,

i want to use the Cityscapes Dataset to train a CNN with Caffe and make some experiments with it, actually i have no idea how to convert the Images and labeling Information of the dataset to the Caffe required levedb or lmdb format.

I successfully created lmdb files with the Caffe internal tool with my own pictures and a corresponding txt-file with the path to the Pictures and the associated labels. But how does this work with the cityscapes dataset? 

Did anybody use this dataset with Caffe before? Any help is appreciated.

Thank you in advance!

Best regards
Stefan

**Comment by mcordts** [comment]
Hi Stefan,

did you check the FCN code and models:
https://github.com/shelhamer/fcn.berkeleyvision.org

The Pascal-Context models are well documented and also the comment section is pretty useful.

Best,
Marius

**Comment by Almo1982** [comment]
Hi Marius,

thank you very much for your quick response, this looks like exactly what i need. I will check this out tonight in Detail!

Stefan

**Comment by Almo1982** [comment]
Hi Marius,

thank you again for your Feedback, i made a big Progress with your related link to the FCN models. Furtheron this is a great tutorial too for my issue:

https://github.com/alexgkendall/SegNet-Tutorial

I will Close this issue then.

Regards
Stefan
