### ISSUE TITLE
KeyError with instance dictKey line 237 of evalInstanceLevelSemanticLabeling.py

### ISSUE THREAD

**Issue by Ellenisawake** [mcordts/cityscapesScripts#41]
Hi, am running the instance seg evaluation and the code doesn't seem to pass with test image where there's no instance. 
While the other images are passed and processed without an issue, it says KeyError with an absolute path to an image with no instance inside. Does anyone have any idea or similar encountering?

**Comment by Ellenisawake** [comment]
seems that we're not supposed to run on test set locally... -->_<--

**Comment by mcordts** [comment]
Exactly, test set evaluation is only possible via our evaluation server: https://www.cityscapes-dataset.com/submit/
