### ISSUE TITLE
Convert labels to 19 classes

### ISSUE THREAD

**Issue by FilippoGrazioli** [mcordts/cityscapesScripts#42]
Hello, 

is there an official script that converts the labels from >30 classes to 19?

Thanks a lot,
Filippo

**Comment by y-kl8** [comment]
Hi, I have the same question. Now, I have ran the  createTrainIdLabelImgs.py to get the  png from .json. But I want to train my net with the label pictures which only have 19 ids.  What should I do to dispose these trainId png?
