### ISSUE TITLE
some questiones about metrics

### ISSUE THREAD

**Issue by kealennieh** [mcordts/cityscapesScripts#43]
Dear authors,

When evaluating the result by running **evalInstanceLevelSemanticLabeling.py**,  we could get AP and AP50%.  I have a question about AP50%. 50% means the threshold of IoU is set as 0.50. However, I'm not sure what IoU represents,  IoU of bounding boxes or IoU of masks ?

Thanks in advance!

**Comment by rohun-tripathi** [comment]
I have a similar Q. I think its the 50% of IoU inside the region. However, who generates the regions for the evaluation?
