### ISSUE TITLE
How to use these scripts?

### ISSUE THREAD

**Issue by lxtGH** [mcordts/cityscapesScripts#51]
I am new to this dataset, I met this problem when I run python cityscapesscripts/preparation/createTrainIdLabelImgs.py
**Failed to find all Cityscapes modules**, I set dataset path in my os environment.(I have install this package, also do the python build)

**Comment by emirarditi** [comment]
I also have this problem when I try to import scripts or use command line tools

**Comment by freedrone** [comment]
same here, it fails to find module annotation

**Comment by Hatuw** [comment]
Maybe you use Python3.x but the code is for Python2.x
I try to print the error by modify the code in `csHelpers.py` (at about line 40):
```
try:
    from annotation   import Annotation
    from labels       import labels, name2label, id2label, trainId2label, category2labels
except Exception as e:
    print(e)
    print("Failed to find all Cityscapes modules")
    sys.exit(-1)
```

And I find that the error is cause by "invalid syntax" but not "Failed to find all Cityscapes modules" (When using Python3.x).

**Comment by freedrone** [comment]
The solution I found was to use scripts locally, installing via pip3 and using that way is frustrating. 

When you use locally, you have to edit all the scripts as the import paths would cause errors.

Just extract the repo to your project root, and use cython too, it speeds things up big time.

Exceptions don't have prints, that is a blindfold in my opinion.

**Comment by lxtGH** [comment]
I agree with you, simple way to solve this problem has two step:
1, use py2 , make , install
2, copy the build result to the cityscape data root directory and then just use the scripts for evaluation

**Comment by tkasarla** [comment]
You can get it to work on Python3 by commenting out the line

    `print type(obj).name`

from cityscapeScripts/helpers/annotation.py line 238

source: https://stackoverflow.com/questions/50220632/deeplab-failed-to-find-all-cityscapes-modules

**Comment by freedrone** [comment]
I'll create a fork, where I deal with having this work with Python3 .

Don't know about Python2.7, rather don't use it anymore... future is now folks: [Python2.7 countdown](https://pythonclock.org/)

**Comment by kinglintianxia** [comment]
@tkasarla idear works fine for me!
Just comment  cityscapeScripts/helpers/annotation.py line 238
```shell
#print type(obj).name
```

**Comment by mcordts** [comment]
Should work with both py2 and 3 now.

**Comment by anamikajnu** [comment]
You can use this piece of code
sys.path.append( os.path.normpath( os.path.join( os.path.dirname("__file__") , '..' , 'helpers' ) ) )
from annotation import Annotation
from anue_labels     import name2label

instead of 
from cityscapesscripts.helpers.annotation import Annotation
from cityscapesscripts.helpers.labels     import name2label
