### ISSUE TITLE
depth matrix problem

### ISSUE THREAD

**Issue by johnlanbor** [mcordts/cityscapesScripts#53]
when i use this matrix to get the real depth

disparity precomputed disparity depth maps. To obtain the disparity values, compute for each pixel p with p > 0: d = ( float(p) - 1. ) / 256., while a value p = 0 is an invalid measurement. Warning: the images are stored as 16-bit pngs, which is non-standard and not supported by all libraries.

I found the d is wrong. the object that near the camera have a big distance,the object that far away is small

**Comment by sr425** [comment]
Hi,
well in disparity, having a small value means the object is far away, having a large disparity in a near object. Disparity is the shift of the same pixel between the left and right camera image. 
Does this answer the question?
