### ISSUE TITLE
how to calculate the real depth?

### ISSUE THREAD

**Issue by zhang-yupeng** [mcordts/cityscapesScripts#55]
hi,
I am confusing about how can i calculate the real depth, i use the formula d = ( float(p) - 1. ) / 256. to calculate the disparity value , and then i  calculate the depth using :  depth = baseline * focal length / disparity value ,  for example:  depth = 0.22*2262/0.13=3828.  i got a very large depth value, is that correct? how can i get a correct real depth?

**Comment by johnlanbor** [comment]
I got the same problem as you
if you have the solution, please let me know

**Comment by johnlanbor** [comment]
@zhang-yupeng according to kitt, I use the PIL to read the imag, the depth is correct.
and i dont found any depth calculate in fastscene. so i think maybe the author preprocessd the depth data

**Comment by OwenHua666** [comment]
What's the unit of this number? I think 0.22 should be 22 mm, which matches 2262 mm. Then, there should be another unit converter for the disparity whose unit is inch/pixel.

**Comment by lylsjtu** [comment]
Hi, How can I get the disparity packages? I wrote the email to cityscapes team but I haven't got any reply.

**Comment by OwenHua666** [comment]
They have to give you the access.

Owen

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lylsjtu** [comment]
Hi,
sorry to bother again,
since cityscapes team have not replied to my email for two weeks,
I wonder if you could kindly send me the download link of 'disparity_trainvaltest.zip' at your convenience.
Thank you!

**Comment by OwenHua666** [comment]
I wish I could, but I don’t think I can distribute it without their permission.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tingZ123** [comment]
@zhang-yupeng  I have the same problem. Is the formula for the depth solution you mentioned the formula used by the author in this article? I am very curious about how the absolute distance value mentioned in the article is implemented.

**Comment by Alexey-Kamenev** [comment]
Cityscapes team specifically mentioned in their [README](../blob/master/README.md#dataset-structure) that disparity PNGs are stored in 16-bit format so you need to read it that way. 
Something like this (baseline and fx are taken from camera JSON file):
```
img_disp_name = '/data/Cityscapes/disparity/train/aachen/aachen_000000_000019_disparity.png'
img_d = cv2.imread(img_disp_name, cv2.IMREAD_UNCHANGED).astype(np.float32)
img_d[img_d > 0] = (img_d[img_d > 0] - 1) / 256

disp = img_d[270, 106]
print(disp)
depth = (0.209313 * 2262.52) / disp
print(depth)
```
```
31.582031
14.995072514849722
```

**Comment by leihe001** [comment]
@lylsjtu how to download disparity data? @all anyone could share me download url? Thank you very much!

**Comment by mcordts** [comment]
Please send us an email mentioning your username, if you need access to the disparity data. We try to reply within a couple of days, if it takes longer an email might have slipped through. Sorry about that. 
Sharing Cityscapes data via other means is not allowed according to our license.

**Comment by zieitokk** [comment]
> Cityscapes team specifically mentioned in their [README](../blob/master/README.md#dataset-structure) that disparity PNGs are stored in 16-bit format so you need to read it that way.
> Something like this (baseline and fx are taken from camera JSON file):
> 
> ```
> img_disp_name = '/data/Cityscapes/disparity/train/aachen/aachen_000000_000019_disparity.png'
> img_d = cv2.imread(img_disp_name, cv2.IMREAD_UNCHANGED).astype(np.float32)
> img_d[img_d > 0] = (img_d[img_d > 0] - 1) / 256
> 
> disp = img_d[270, 106]
> print(disp)
> depth = (0.209313 * 2262.52) / disp
> print(depth)
> ```
> ```
> 31.582031
> 14.995072514849722
> ```
Hi Alexey,

I have tried your formula to calculate the depth. However, there still exist some problems that bother me.
1. Since the disparity map have lots of **ZERO** values in their .png file, we will get lots of **inf** depths. We are not able to evaluate the RMSE, RMSE_log and etc.
2. If we use 

> float(d -1.)/256.

we change those **ZERO**s into negative numbers and they will later be calculated into huge negative depths.

I got confused about the transformation between these two formula.   So would you mind telling me if you have encountered such issues and how you would solve them? Thank you!

**Comment by Joeper214** [comment]
Hi, @mcordts 
> Sharing Cityscapes data via other means is not allowed according to our license.

I'm adding support for CityScapes Dataset Loader in my opensource project. Is it okay to add some of the files as one of our test case fixtures? 

As what I've read in the license agreement I did not see any information about Open Source Projects. S

**Comment by jilner** [comment]
> Cityscapes team specifically mentioned in their [README](../blob/master/README.md#dataset-structure) that disparity PNGs are stored in 16-bit format so you need to read it that way.
> Something like this (baseline and fx are taken from camera JSON file):
> 
> ```
> img_disp_name = '/data/Cityscapes/disparity/train/aachen/aachen_000000_000019_disparity.png'
> img_d = cv2.imread(img_disp_name, cv2.IMREAD_UNCHANGED).astype(np.float32)
> img_d[img_d > 0] = (img_d[img_d > 0] - 1) / 256
> 
> disp = img_d[270, 106]
> print(disp)
> depth = (0.209313 * 2262.52) / disp
> print(depth)
> ```
> 
> ```
> 31.582031
> 14.995072514849722
> ```
Hello.  What are the units of the baseline?Thank you.

**Comment by dreamPoet** [comment]
I found the reply of Alexey was quite useful and got the right depth. However, when I try reconstructing the 3D point clouds with these computed depths and RGB images, I get wrong results... does anyone know why?
