### ISSUE TITLE
Report on empty gtFine annotations

### ISSUE THREAD

**Issue by xiongzhanblake** [mcordts/cityscapesScripts#57]
Hi,
recently I downloaded gtFine_trainvaltest.zip from the website [Cityscapes](https://www.cityscapes-dataset.com/downloads/).  However, when I unzipped it and looked into the test folder, I found all annotation images are almost empty without any labels on objects.

Is there something wrong?

**Comment by sr425** [comment]
Hi,
I can only guess, but in most benchmarks groundtruth is not given for test images, as the test images are used to compute the benchmark scores and users could train their algorithms also on these images, giving less information about generalization. But I do not know why they included those empty groundtruths. Therefore empty images should be correct.

**Comment by mcordts** [comment]
That's intended. The test folder does not contain any annotations, except for which is known from camera calibration, i.e. the rectification artifacts and the ego vehicle. In order to evaluate on the test set, you need to submit your results to our evaluation server.
