### ISSUE TITLE
how to download the dataset that need request

### ISSUE THREAD

**Issue by nanhailongwang** [mcordts/cityscapesScripts#59]
I am a Ph.D. candidate of Xiamen University in China. My research is focused on depth estimation and semantic segmentation. Recently I need to use your packages named leftImg8bit_sequence_trainvaltest.zip and camera_trainvaltest.zip of cityscapes dataset. But the website shows "The following packages are available upon request". In order to complete my research, I need your permission to download these two package.

**Comment by tano297** [comment]
I have requested the same a couple of weeks ago to the email address, and I had no response. Is there a formal way to request these files? There is no mention of how on the website.
Thanks!!!

**Comment by mcordts** [comment]
You both have access to the requested packages, the easiest way for such requests is to send us an email.

**Comment by abdur75648** [comment]
Hi @nanhailongwang @tano297 
if anyone of you have got the "leftImg8bit_sequence_trainvaltest" (324GB) dataset, could you share just the "validation" split of it with me, please? I am having trouble downloading it.
Let me know if it's possible for you to share a download link with me on my email
