### ISSUE TITLE
Problem with evalPixelLevelSemanticLabeling.py 

### ISSUE THREAD

**Issue by Timo-hab** [mcordts/cityscapesScripts#6]
Dear Marius Cordts

I try to evaluate my results, but when I run this script I get the following error:

Found no prediction for ground truth /home/timo/Cityscapes/gtFine/val/frankfurt/frankfurt_000001_065617_gtFine_labelIds.png

My call in the terminal: python evalPixelLevelSemanticLabeling.py 

I created a folder "results" in the root directory. Inside is a image, where pixels encode the class IDs as defined in labels.py: frankfurt_000001_011835* .png 
The image is from the ground truth values: /home/timo/Cityscapes/gtFine/val/frankfurt
The result should therefore be 100%, but the above error occurred.

If I use the following call:  python evalPixelLevelSemanticLabeling.py /path/to/ground_truth/prediction
I get only a lot of "nan" as output. 
Could you please give me a hint?

Best,
Timo

**Comment by mcordts** [comment]
Hi Timo,

do you have a single result image or result images for all ground truth
frames? The latter is what you need, otherwise the tool complains.

Best,
Marius

2016-06-20 11:55 GMT-07:00 Timo-hab <notifications@github.com>:

**Comment by Timo-hab** [comment]
I see. Thank you for your quick response!

**Comment by MFattouh** [comment]
Sometimes, if one ignored most of the labels, some images will have only unlabeled (ignored) annotations. Would be great to skip those images.
