### ISSUE TITLE
Hi, I‘m looking for the download link for the leftImg8bit_sequence_trainvaltest.zip dataset...

### ISSUE THREAD

**Issue by mengfansheng16** [mcordts/cityscapesScripts#61]
Hi, Marius：
Sorry to bother again！
Where is the download link for the [leftImg8bit_sequence_trainvaltest.zip](https://www.cityscapes-dataset.com/downloads/) dataset?
I have been looking for two weeks and sent a message to your [email address.](mail@cityscapes-dataset.net)
My account is **mengfansheng16**.
Please help me to reply to the email at your convenience. 
I wish you all the best, thank you very much.
Fan-sheng Meng

**Comment by mcordts** [comment]
Contacting via email is the right thing to do, not via an issue on Github. You already have access and it appear that you already downloaded the data.

**Comment by xuyufan936831611** [comment]
Hi, Marius:
I'm sorry to bother you. I met the same problem that I have request the  download link for the _leftImg8bit_sequence_trainvaltest.zip_ and _camera_trainvaltest.zip_ dataset via email for several weeks, but I didn't receive their reply.
Please help me to reply to the email at your convenience.
Thanks and best wishes!
Yufan Xu

**Comment by ezorfa** [comment]
Hi @mengfansheng16 !

What is the size of the leftImg8bit_sequence_trainvaltest.zip dataset that you have access to?

I have access to the dataset with the same name which is about 324GB but I am looking for 110GB one.

**Comment by wangchuan** [comment]
@mcordts Hi, I just sent you an email for requesting this dataset, but I have not received any response yet. My account name is `cwang.hku`, Could you send me the link? Thank you so much!

**Comment by Skywalker666666** [comment]
Anybody know what is the size of leftImg8bit_sequence_trainvaltest.zip, why there are two versions with 324GB and 110GB respectively? thanks in advance.

**Comment by kartikeya13** [comment]
Anybody knows what does http://leftimg8bit_sequence_trainvaltest.zip/ contains? are these just the raw images?

**Comment by zhe-juanz** [comment]
> 
Hi,
on the web https://www.cityscapes-dataset.com/downloads/上，
I only found 324G files, but I didn't find the 110G file you said

The file name is：

[leftImg8bit_sequence_trainvaltest.zip (324GB)
](https://www.cityscapes-dataset.com/file-handling/?packageID=14) [[md5]](https://www.cityscapes-dataset.com/md5-sum/?packageID=14)
30-frame snippets (17Hz) surrounding each left 8-bit image (-19 | +10) from the train, val, and test sets (150000 images)

Bset,
Zhe

**Comment by abdur75648** [comment]
Hi @mengfansheng16 @ezorfa @wangchuan @Skywalker666666 @kartikeya13 @zhe-juanz 
if anyone of you have got the "leftImg8bit_sequence_trainvaltest" (324GB) dataset, could you share just the "validation" split of it with me, please?
Let me know if it's possible for you to share a download link with me on my email
