### ISSUE TITLE
Error: Failed to find all Cityscapes modules 

### ISSUE THREAD

**Issue by Minotaur-CN** [mcordts/cityscapesScripts#64]
Hi, all,

Some error happens when running following scripts.
cityscapesScripts-master/cityscapesscripts/preparation/createTrainIdLabelImgs.py

**Comment by LeeTruth** [comment]
@Minotaur-CN 您好，我遇到了和您一样的问题，请问您是怎样解决的呢

**Comment by zl535320706** [comment]
> @Minotaur-CN 您好，我遇到了和您一样的问题，请问您是怎样解决的呢

maybe you should use python2 instead.
and you can refer https://github.com/mcordts/cityscapesScripts/issues/51
