### ISSUE TITLE
Test 

### ISSUE THREAD

**Issue by InstantWindy** [mcordts/cityscapesScripts#65]
Can you tell me how to test the mean iou in the cityscape test set online? Because the cityscape test set has no tags, online testing is required, but I don't know what to do.I uploaded the test results as he asked, but there was always Content of zip archive does not match specifications. Not all predictions for all images were found. Thank you very much！

**Comment by mcordts** [comment]
The requirements are described on top of the Submit button. In your case, the predictions do not follow the pattern "berlin_000123_000019*.ext" or there are not enough predictions (exactly 1 file per test set image required).
