### ISSUE TITLE
Number of analyzed pixels and entries in confusion matrix disagree

### ISSUE THREAD

**Issue by chichilicious** [mcordts/cityscapesScripts#66]
The only modifications to the code I've made are set the rootPath to my directory where the segmented images are present and the cityscapesPath is the path to my ground truth.
My grountruth file should be "_gtFine_labelIds.png" right?
The shape of my gt and images are the same.
Error:
```
Evaluating 500 pairs of images...
ERROR: Number of analyzed pixels and entries in confusion matrix disagree: contMatrix 2093891, pixels 2097152
Segmentation fault (core dumped)
```

**Comment by mcordts** [comment]
I assume that your predictions contain invalid label Ids. All IDs must be between 0 and 33.
