### ISSUE TITLE
mapping "ignore" labels during evaluation

### ISSUE THREAD

**Issue by beejisbrigit** [mcordts/cityscapesScripts#68]
In one of the previous issues, the following suggestion was given for which label should be used during training:

"I would use the IDs that we named trainId for training. The idea is to map labels that are ignored to 255 and to have consecutive IDs for all other labels. However, please make sure to reverse this mapping before evaluation."

My question is, how do you reverse the mapping before before evaluation? If several labels are mapped to "ignore/void" during training, it will be difficult if not impossible to map back to the original label at test time. Do you just mean if you change the labels to your own unique class ids, you need to map back to the original Cityscapes class ids?

**Comment by mcordts** [comment]
You need to map your predicted IDs to the original set in 0...33. Most deep learning methods will not predict "ignore/void" and hence these classes do not need to be mapped back. Does that explain your question?
