### ISSUE TITLE
ImportError: No module named cityscapesscripts.helpers.csHelpers

### ISSUE THREAD

**Issue by 408550969** [mcordts/cityscapesScripts#74]
Hi, when I run createTrainIdLabelImgs.py, this error occurred. How can I solve it?

**Comment by manutom** [comment]
@408550969  what is the solution?

**Comment by 408550969** [comment]
sudo pip install cityscapesscripts

**Comment by xiaoli0000** [comment]
Hi, when I run sh convert_cityscapes.sh, this error occurred. How can I solve it?

**Comment by xiaoli0000** [comment]
@408550969
