### ISSUE TITLE
How to evaluate mAP with no instances detected?

### ISSUE THREAD

**Issue by fabvio** [mcordts/cityscapesScripts#75]
Hi, we have a network that has been trained in a particular way, and sometimes it hasn't a great accuracy. We noticed that, for the mAP calculation in instance segmentation, the script requires at least one prediction per frame. However, there are frames where we fail to detect any instance. How can we run an evaulation on those? Thanks in advance.

**Comment by mcordts** [comment]
Hi, did you try to create an empty .txt file for those frames where you have no prediction?

**Comment by mcordts** [comment]
What is the error message/stacktrace?
