### ISSUE TITLE
Camera Properties 

### ISSUE THREAD

**Issue by acvictor** [mcordts/cityscapesScripts#76]
What's the field of view of the camera lens used here?

**Comment by mcordts** [comment]
Hi, you could compute that based on the calibration data provided. Please refer to the Readme and docs in this repo.

**Comment by acvictor** [comment]
Size of the sensor d = 5.8 mm
Pixel size = 2.2 µm
Focal length f = 2262 x 2.2 µm = 4.9764 mm

FoV = 2arctan(d/2f) _assuming the lens is focused at infinity_
        = ~60°
 
Does this seem correct?

**Comment by mcordts** [comment]
That sounds reasonable!

**Comment by jilner** [comment]
> Size of the sensor d = 5.8 mm
> Pixel size = 2.2 µm
> Focal length f = 2262 x 2.2 µm = 4.9764 mm
> 
> FoV = 2arctan(d/2f) _assuming the lens is focused at infinity_
> = ~60°
> 
> Does this seem correct?

How can I get the Focal length f, i.e.2262 and  2.2.  Thank you!

**Comment by I3aer** [comment]
Hi,

Could you please tell me where the camera folder? In calibrationpfd it is said that the intrinsic and extrinsic parameters are in the camera folder.
Thank you

**Comment by acvictor** [comment]
@jilner I got those values by looking up the sensor they used.
