### ISSUE TITLE
How to convert trainIds to labelIds

### ISSUE THREAD

**Issue by ktnguyen2** [mcordts/cityscapesScripts#78]
I have images with Ids mapped 0-255, and am seeking to convert them to 0-34 so I can run eval code.

I know this has been brought up in Issue #19, but there was no solution posted.

**Comment by mcordts** [comment]
This step is part of your method. Most implementations use the mapping from [labels.py](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py).
Note that all labels with `ignoreInEval==True` are ignored during evaluation and hence you don't need to produce these with your method.

**Comment by ktnguyen2** [comment]
Hi, thank you so much for your quick response. I did realize that converting them was part of the method, and now am dealing with 19 classes. However, when I try to run evalPixelLevelSemanticLabeling.py, I get this error:

`Traceback (most recent call last):
  File "evalPixelLevelSemanticLabeling.py", line 696, in <module>
    main()
  File "evalPixelLevelSemanticLabeling.py", line 690, in main
    evaluateImgLists(predictionImgList, groundTruthImgList, args)
  File "evalPixelLevelSemanticLabeling.py", line 478, in evaluateImgLists
    nbPixels += evaluatePair(predictionImgFileName, groundTruthImgFileName, confMatrix, instStats, perImageStats, args)
  File "evalPixelLevelSemanticLabeling.py", line 605, in evaluatePair
    confMatrix[gt_id][pred_id] += c
IndexError: index 34 is out of bounds for axis 0 with size 34`

Do you have any idea what the problem could be?

**Comment by mcordts** [comment]
yes, the highest label id is 33, you predict 34 or larger.

**Comment by ktnguyen2** [comment]
Hello,

I am still confused. If I have 19 classes and I am using trainid2label, is this okay?

**Comment by mcordts** [comment]
Yes, should be fine.

**Comment by ktnguyen2** [comment]
Hello,

That's what I have been doing and I am getting the error previously posted.

**Comment by Vieeo** [comment]
> Hello,
> 
> I am still confused. If I have 19 classes and I am using trainid2label, is this okay?

hello，where is trainid2label? I want to convert 19 cls into 34 cls, thanks!
