### ISSUE TITLE
Error using eval code

### ISSUE THREAD

**Issue by ktnguyen2** [mcordts/cityscapesScripts#79]
Hello,

Sorry if I am beating a horse to death. I am still having an issue with my code, but my original post has been closed (see issue #78 ).

I am using the[ Keras version of PSPNet](https://github.com/Vladkryvoruchko/PSPNet-Keras-tensorflow), with 19 as my number of classes and trainid2label as my mapping. This is the error that I am getting:

Traceback (most recent call last):
File "evalPixelLevelSemanticLabeling.py", line 696, in 
main()
File "evalPixelLevelSemanticLabeling.py", line 690, in main
evaluateImgLists(predictionImgList, groundTruthImgList, args)
File "evalPixelLevelSemanticLabeling.py", line 478, in evaluateImgLists
nbPixels += evaluatePair(predictionImgFileName, groundTruthImgFileName, confMatrix, instStats, perImageStats, args)
File "evalPixelLevelSemanticLabeling.py", line 605, in evaluatePair
confMatrix[gt_id][pred_id] += c
IndexError: index 34 is out of bounds for axis 0 with size 34

I would appreciate any help.

**Comment by mcordts** [comment]
The error message indicates that it found an ID 34 in either the ground truth or the prediction file. You would need to debug into this.
If this happens only for a single file, you could try to add a try...catch around the line and print the file names in the catch block. You could identify occuring IDs by loading the prediction and groundtruth images using numpy and printing their unique IDs.

**Comment by ktnguyen2** [comment]
Thank you for your advice. I will try this out and let you know what I find!
