### ISSUE TITLE
[Bug Report] Panoptic Image Save Type 

### ISSUE THREAD

**Issue by Angzz** [mcordts/cityscapesScripts#83]
Hi, @alexander-kirillov , I find some errors for your save type for the panoptic image, for the https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createPanopticImgs.py#L133

It seems that for the 0th channel, if the pixels > 1000, just % 256 will generate a useless pixel but no the category info, and will confuse the training, so I think you should correct as follows:

``
color = [segmenticId % 256, segmentId // 256, segmentId // 256 // 256]
``

that is use `segmenticId` for the 0th channel but not the `segmentId`.

**Comment by alexander-kirillov** [comment]
Dear Ang,

In the script `color` encodes `segmentId` in PNG by splitting it into three `uint8` values. You can take a look at [Panoptic COCO format](http://cocodataset.org/#format-data) that has more information about the encoding. When read it allows to connect segments from the PNG and segment information written in `segment_info` field of the corresponding JSON file. 

I'm not sure how this can confuse a training procedure. Could you please explain it in more details?

Let me know if you have any further questions.
