### ISSUE TITLE
Does Instance Segmentation Cityscapes's Annotation datasets exist?

### ISSUE THREAD

**Issue by hoanganhtuanfsoft** [mcordts/cityscapesScripts#84]
I want to train Mask R-CNN on cityscapes. But I don't know where annotation of instance segmentation is?. It is generated by createTrainIdInstanceImgs.py ? (using json files?)

Please confirm me if i wrong. 

Thanks a lot.

**Comment by Angzz** [comment]
yes, just use this scripts.
