### ISSUE TITLE
The access to the 'packages which are available upon request'

### ISSUE THREAD

**Issue by liuziyang123** [mcordts/cityscapesScripts#85]
Hi, 
Lately I have been working on video semantic segmentation tasks. So I sent an email to this address mail@cityscapes-dataset.net 10 days ago, to applying for 'leftImg8bit_sequence_trainvaltest.zip' and 'timestamp_sequence.zip'. But I get no responses.
Is this email address correct? Or what else do I need to do?
Many thanks to your work in semantic segmentation. I will be very appreciate if I can get the access to your datasets.

**Comment by JoeFang123** [comment]
I have the same question with you, and I wonder whether you have solved it?

**Comment by chenchao15** [comment]
me too

**Comment by mcordts** [comment]
Sending an email to that address is the best way. Sorry for the occasional delays. If we didn't react by now, the emails might have slept through, please ping us again (via email).

**Comment by abdur75648** [comment]
Hi @liuziyang123 @JoeFang123 @chenchao15 
if anyone of you have got the "leftImg8bit_sequence_trainvaltest" dataset, could you share just the "validation" split of it with me, please?
Let me know if it's possible for you to share a download link with me on my email
