### ISSUE TITLE
How to download Cityscapes video sequences dataset ?

### ISSUE THREAD

**Issue by phongnhhn92** [mcordts/cityscapesScripts#86]
Hi guys, 
I would like to have work on driving sequences with camera pose for each frame.

I would like to ask how to download Cityscapes video sequences dataset ? As I can see in the website, there are a few packages available upon request such as : LeftImg8bit_sequence_trainvaltest.zip,timestamp_sequence.zip,vehicle_sequence.zip.

Is there anyway to download those files which I guess contains what I need for my research. Thanks !

**Comment by jiaqixuac** [comment]
Hi @phongnhhn92 , sorry to bother you.

Did you download the sequence data and how? Thanks a lot if you can help.
