### ISSUE TITLE
Create instanceID image with different classes

### ISSUE THREAD

**Issue by viet2411** [mcordts/cityscapesScripts#88]
Hello everyone,
Because the instancesId images in downloaded files only contain instancesId from 8 classes (car,truck,train,person,bus,rider,bicycle,motorcycle), so I'm trying to use createTrainIdInstanceImgs.py to generate images that contain instance from other classes. But I do not know where to change classes in this code. Can anybody show me how to do?

**Comment by mcordts** [comment]
You could modify the column `hasInstances` in [labels.py](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/helpers/labels.py) and re-run the script. However, as we did not annotate other classes with individual polygons, the instance ids won't be useful.
