### ISSUE TITLE
Sample input for instance segmentation evaluation

### ISSUE THREAD

**Issue by kHarshit** [mcordts/cityscapesScripts#93]
Hi,

Can someone provide me with the sample input required to evaluate instance segmentation?

https://github.com/mcordts/cityscapesScripts/blob/878f1d05b1676c669d977a91831ea800482e36c4/cityscapesscripts/evaluation/evalInstanceLevelSemanticLabeling.py#L13

```
# To run this script, make sure that your results contain text files
# (one for each test set image) with the content:
#   relPathPrediction1 labelIDPrediction1 confidencePrediction1
#   relPathPrediction2 labelIDPrediction2 confidencePrediction2
#   relPathPrediction3 labelIDPrediction3 confidencePrediction3
#   ...
```

How do I create the above mentioned txt file? Do multiple files need to be created (one for each label) per image? Can you provide sample file for one image?

**Comment by mcordts** [comment]
Hi,
You'll need to write a script that creates these files. You need one .txt file per image. Each .txt file points to one instance prediction. Each instance prediction is a .png image. As the predictions might be overlapping, they cannot be represented in a single .png, hence the .txt/.pngs representation.
Best,
Marius

**Comment by kHarshit** [comment]
> Hi,
> You'll need to write a script that creates these files. You need one .txt file per image. Each .txt file points to one instance prediction. Each instance prediction is a .png image. As the predictions might be overlapping, they cannot be represented in a single .png, hence the .txt/.pngs representation.
> Best,
> Marius

Thanks, I solved the issue.

**Comment by Sunyingchun** [comment]
@kHarshit Hi, I have encountered the same problem as you. Could you give me some advice on how to write a script that creates these files?
