### ISSUE TITLE
leftImg8bit_trainvaltest_foggy.zip 

### ISSUE THREAD

**Issue by yyfyan** [mcordts/cityscapesScripts#96]
Hi

I'm a graduate student at Wuhan university of technology from China.
And my research is image dehaze and segmentation.

I would like to use Cityscape and Foggy Cityscape to validation my research.
Can you give me access to download leftImg8bit_trainvaltest_foggy.zip ? thanks.
Best regards,

**Comment by mcordts** [comment]
Please send us an [email](mailto:mail@cityscapes-dataset.net) and include your username there.
